### ISSUE TITLE
[soap:Client] Unmarshalling Error: cvc-complex-type.3.2.2: Attribute 'id' is not allowed to appear in element 'ns1:positions'

### ISSUE THREAD

**Issue by niels-numbers** [baltpeter/internetmarke-php#11]
Besides the fix in #3, the following example still leads to a crash `[soap:Client] Unmarshalling Error: cvc-complex-type.3.2.2: Attribute 'id' is not allowed to appear in element 'ns1:positions'`

```
$order_item = new \baltpeter\Internetmarke\OrderItem(1, null, null,
    new \baltpeter\Internetmarke\Position(1, 1, 1), 'FrankingZone');

$x = $service->checkoutShoppingCartPNG($user_token, [$order_item,$order_item], 160);
```

I also don't know how to fix it, besides just making a deep copy like this:

```
  public function checkoutShoppingCartPng($user_token, $positions, $total, $shop_order_id = null,
                                            $ppl_id = null, $create_manifest = null, $create_shipping_list = null) {

        $distinct_positions = [];
        foreach ($positions as $position) {
          $distinct_positions[] = deep_copy($position);
        }

        $result = $this->__soapCall('checkoutShoppingCartPNG', array('CheckoutShoppingCartPNGRequest' => array(
            'userToken' => $user_token, 'shopOrderId' => $shop_order_id, 'ppl' => $ppl_id, 'positions' => $distinct_positions,
            'total' => $total, 'createManifest' => $create_manifest, 'createShippingList' => $create_shipping_list
        )));
```

Maybe I overlook something, but isn't the error only appearing in 
 `checkoutShoppingCartPdf` and `checkoutShoppingCartPng`? If thats the case, we could get rid of all deep copy calls that where introduced in #3. 

If thats correct, then I could make a PR to fix it.

**Comment by baltpeter** [comment]
Interesting, I have not caught that when testing 8082188. Unfortunately, I also don't have a Portokasse test account anymore which makes testing things like this pretty much impossible, so I can't offer any insight here.

Have you tried if the change you are proposing solves the issue? If so, I am fine with implementing that.

As for the rather generous use of `deep_copy()` in 8082188, I know that some of these copies are probably not necessary but I would rather be on the safe side. As per the commit message: "To make sure a similar issue cannot occur in the future, I have applied this procedure to all case where a non-primitive value is assigned through a setter."

**Comment by niels-numbers** [comment]
> Have you tried if the change you are proposing solves the issue? If so, I am fine with implementing that.

Yes, it works. I will create a PR for that.

> As for the rather generous use of `deep_copy()` in [8082188](https://github.com/baltpeter/internetmarke-php/commit/80821887698a5dbaa64db68a228bedd038b8ec1e), I know that some of these copies are probably not necessary but I would rather be on the safe side. As per the commit message: "To make sure a similar issue cannot occur in the future, I have applied this procedure to all case where a non-primitive value is assigned through a setter."

Okay, maybe its better to be safe and have redundant copies, rather then getting errors later. 
I also noticed that while my above solution worked:

`'positions' => array_map("DeepCopy\deep_copy", $positions)`

this does not work (I don't understand why)


`'positions' => deep_copy($positions)`
