### ISSUE TITLE
unzipPNG function

### ISSUE THREAD

**Issue by Dieterfu** [baltpeter/internetmarke-php#15]
Hello,

is there an example how to use the unzipPNG function?

Thank you.
Best Regards,
Dieter

**Comment by baltpeter** [comment]
Hi,

I don't think there is an example for that yet, no. That feature was contributed in #10, I haven't actually used it myself.

Seems pretty easy to use, though:

```php
  /**
   * Store zip and png files in folder of $path
   * @param string $path location where png should be extracted to
   * @return array on success: filenames of png's that were extracted
   *               on failure: if copy of zip file failed false,
   *                           if zip coulnd not be opened the error code
   */
  public function unzipPNG($path)
```

Essentially, just order the stamps as described in the [wiki](https://github.com/baltpeter/internetmarke-php/wiki/Examples#buying-actual-stamps) and call `$stamp->unzipPNG('/some/dir');` with the directory you want the PNGs to be extracted to. (On success) this function will return an array of the extracted files.

Cheers,
Benni
