### ISSUE TITLE
more than 1 order items

### ISSUE THREAD

**Issue by technonur** [baltpeter/internetmarke-php#17]

**Comment by technonur** [comment]
i fixed it

**Comment by Gustavoson** [comment]
I need your help!
How you fixed it? 
I try to add more objects in the array, but nothing works.

**Comment by technonur** [comment]
hi,
can you send me your code i will check it.

Am Di., 23. Nov. 2021 um 11:03 Uhr schrieb Gustavoson <
***@***.***>:
