### ISSUE TITLE
How I can get availible Products from Prodws

### ISSUE THREAD

**Issue by 123bistami** [baltpeter/internetmarke-php#2]
Hello,

can somebody help me, how can i get availible products from ProdWs, which header paramaeters i have to send is the mandant id same like the Partner ID, example request with headers an endpoint pls.

BR

**Comment by 123bistami** [comment]
Can You help me to build this ws security header for PHP:

 <soapenv:Header><wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"><wsse:UsernameToken wsu:Id="UsernameToken-47695D4677F169938C14458490956322"><wsse:Username>USERNAME</wsse:Username><wsse:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordText">PASSWORD</wsse:Password></wsse:UsernameToken></wsse:Security></soapenv:Header>

Thanks

**Comment by Structed** [comment]
In case someone else finds this issue and is frustrated, that they cannot find a solution: I finally made one: https://github.com/Structed/prodws
