### ISSUE TITLE
Where to find ProductCode ?

### ISSUE THREAD

**Issue by hhansen06** [baltpeter/internetmarke-php#20]
I'm unable to find the definition for the Product_Code List. 
So in OrderItem, ProductCode 1 is a 0,80€ Letter?
What ProductCode would a 1,45€ Letter be?

**Comment by baltpeter** [comment]
I am not aware of a public list of the product codes.

You either have to register for DPAG's separate ProdWS or request a CSV from them via email.

**Comment by xolf** [comment]
@hhansen06 you can use their online product configurator: https://shop.deutschepost.de/shop/internetmarke/imConfiguration.jsp and have a look for the `addon-combinations.json` requests. There you find the product codes for each product in the `pplId` column.
