### ISSUE TITLE
Portokasse Login 

### ISSUE THREAD

**Issue by niels-numbers** [baltpeter/internetmarke-php#7]
Hey,

thank you for this awesome package, it was helping me a lot.

I noticed that there is no class for "Portokasse laden" (see Technische Beschreibung page 15). 
I think its useful to have such a class with all properties that are relevant for the form and a method to compute the special signature. Shall I add this as a PR or do you not want this is in your project?

**Comment by baltpeter** [comment]
Hi,

thanks for the issue. Glad the package is helping you!

If I remember correctly, that endpoint didn't exist back when I implemented most of the functionality. But it does seem indeed seem useful. If you want to implement that and submit a PR that would be great, thanks.

Cheers,
Benni
