### ISSUE TITLE
Create improved return object for checkoutShoppingCartPng?

### ISSUE THREAD

**Issue by niels-numbers** [baltpeter/internetmarke-php#8]
Hi,

I noticed that checkoutShoppingCartPng returns a stdClass. When one wants to access the png or png's, then this is a difficult task, because the stdClass only points to a zip file. 

I thought maybe we could replace the stdClass with a proper class that contains a method to unzip it and returns an array of the url's to the pictures. As a parameter one would have to give a path to the directory where the images and the zip file should be unzipped. And the new class should be so, that it does not break old code.

Shall I create a PR for this or do you not like it?

**Comment by baltpeter** [comment]
Hi again,

also thank you for this issue.

The original idea behind this package was to provide a very minimal wrapper around the SOAP API from DPAG that could later be wrapped again in another package that would abstract away this API into something more sane and maybe even implement other services (like DHL, Hermes etc.). However, I never got around to that and now I don't really need it anymore myself.

Regardless, I feel like the feature you're proposing doesn't really conflict with that original idea. It doesn't change the API 'specification' but rather only adds a PHP-specific convenience feature. That sounds fine to me.
So again, if you would like to build that and submit a PR, I would appreciate that.

Thanks,
Benni
